### PR TITLE
Fixes #3930. Tests are crashing again...

### LINKED ISSUE #3930: Tests are crashing again...
This is intermittent and non-deterministic.

Image

Image

I "fixed" this previously, but was not sure what I actually did to fix it.

Some test is failing in such a way that it's causing the test process to crash. Pretty sure (based on prior experience) it's NOT the test identified above as it changes from run to run.

If anyone has more experience with these things than I, I'd love help.

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3930

## Proposed Changes/Todos

- [x]  Overridden `Settings.Sources` needs to be cleared explicitly if `Application.Reset` or `Application.Shutdown` aren't called

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: UnitTests/Configuration/GlyphTests.cs [hunk 1]
```diff
@@ -45,6 +45,7 @@ public void Overrides_Defaults ()
 
         // clean up
         Locations = ConfigLocations.All;
+        Settings.Sources.Clear ();
```
Comment (tig) [inline UnitTests/Configuration/GlyphTests.cs:48]: Just call CM.Reset()?

**Review by tig — CHANGES_REQUESTED** [review]

**Comment by tig** [comment]
How did you discover that this was the cause?

**Comment by BDisp** [comment]
> How did you discover that this was the cause?

After an unit test fail, that running alone doesn't fail, you need to run it together with each unit test namespace. When the test fail again, run with each unit test on that namespace until the test fail again. Now debug both unit tests together to find the cause.

**Review by tig — APPROVED** [review]
