### PR TITLE
Fixes #3144. TextView Autocomplete does not insert capital letters

### LINKED ISSUE #3144: TextView Autocomplete does not insert capital letters
**Description**
When using autocomplete inside of a TextView, the committed suggestion is converted to lowercase.

I believe this is due to the characters being cast to a KeyCode before being turned into a Key object instead of using the overload of the Key constructor that takes a char.

**To Reproduce**
I am able to reproduce this in v2_develop branch in the UICatalog.
1. Go to Editor scenario
2. Enable AutoComplete in the dropdown menu
3. Start typing 'Hello' (or another word that exists in the text.
4. See suggestion 'Hello'
5. Select 'Hello' in the autocomplete popup
6. Note that the inserted text is converted to all lowercase ('hello' instead of 'Hello')

**Expected behavior**
Autocomplete suggestions in TextView should replace text with the suggestion provided and not convert it to lowercase. 
**Screenshots**
terminalgui_autocomplete_enable
terminalgui_autocomplete
terminalgui_autocomplete_completed

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro

### PR DESCRIPTION
**Pull request by joebart457**
Fixes #3144. TextView Autocomplete does not insert capital letters

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- Have 2 failing tests I believe to be unrelated to the changes in this PR
- I believe this issue is captured in #3141 
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: UnitTests/Text/AutocompleteTests.cs [hunk 1]
```diff
@@ -153,7 +153,7 @@ public void KeyBindings_Command ()
 			Assert.Equal (3, g.AllSuggestions.Count);
 			Assert.True (tv.NewKeyDownEvent (new (tv.Autocomplete.SelectionKey)));
 			tv.PositionCursor ();
-			Assert.Equal ($"fortunately Fortunately super feature.", tv.Text);
+			Assert.Equal ($"Fortunately Fortunately super feature.", tv.Text);
```
Comment (BDisp) [inline UnitTests/Text/AutocompleteTests.cs:156]: With this change I'm seeing that this issue already existed before the Key class implementation. Good catch.

**Review by tig — APPROVED** [review]
Lovely catch. Appreciate it!
