### PR TITLE
Fixes #2944. `TreeView` unit tests fail intermittently: Ensures `Attribute` and `Color` are read only value types

### LINKED ISSUE #2944: `TreeView` sometimes causing unit test failure
This test `Terminal.Gui.ViewsTests.TreeViewTests.TestTreeViewColor` sometimes fail and we need to check why.
```
  Failed Terminal.Gui.ViewsTests.TreeViewTests.TestTreeViewColor [43 ms]
  Error Message:
   System.Exception : Unexpected color White,Black was used at row 0 and col 0 (indexes start at 0).  Color value was White,Black (expected colors were -1,0)
  Stack Trace:
     at Terminal.Gui.TestHelpers.AssertDriverColorsAre(String expectedLook, ConsoleDriver driver, Attribute[] expectedColors) in /home/runner/work/Terminal.Gui/Terminal.Gui/UnitTests/TestHelpers.cs:line 336
   at Terminal.Gui.ViewsTests.TreeViewTests.TestTreeViewColor() in /home/runner/work/Terminal.Gui/Terminal.Gui/UnitTests/Views/TreeViewTests.cs:line 868
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

_Originally posted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/2941#issuecomment-1785333871_

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- Fixes #2944 

## Todo:

- [x] Make `Color` a readonly value type with unit test to prove it
  - [x] Change `Color.ColorName` to be `get` only. We're lucky in that the only code in the project that does `someAttribute.ColorName = colorName` are in unit tests! To convince myself I'm correct on this, I commented out all those tests that set `ColorName` and the TreeView case no longer fails.
  - [x] Change `Color.R/G/B/A/Rgba/` to be `get` only.
- [x] Fix things that the above broke
- [x] Beef up unit tests

## For another time:

- [ ] Change `ColorScheme` in the same way. I spent an hour yesterday on an issue where I had done `var cs = colorScheme` vs `var cs = new ColorScheme(colorScheme)`. This one is gonna be harder, as there's tons of code that will break, I fear.  We'll do this in : https://github.com/gui-cs/Terminal.Gui/issues/2381

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by tig** [comment]
On this:

- [ ] Change `Attribute.Default` to be a `static` dynamic `property` with only a `get`er.

Now that both `Color` and `Attribute` are value types, this is no longer needed, so I took it back to the way it was before as it's slightly more performant...

```cs
[JsonConverter (typeof (AttributeJsonConverter))]
public readonly struct Attribute : IEquatable<Attribute> {
	/// <summary>
	/// Default empty attribute.
	/// </summary>
	/// </remarks>
	public static readonly Attribute Default = new (Color.White, Color.Black);
```

File: UnitTests/Drawing/AttributeTests.cs [hunk 1]
```diff
@@ -47,7 +50,7 @@ public void ColorNamesConstructor ()
 		Assert.Equal (new Color (Color.Blue), attribute.Background);
 	}
 
-	[Fact, AutoInitShutdown]
+	[Fact] [AutoInitShutdown]
```
Comment (BDisp) [inline UnitTests/Drawing/AttributeTests.cs:53]: If we do a format with Ctrl+K/Ctrl+D it will change to this:

```cs
[Fact]
[AutoInitShutdown]
```

I really don't understand why you can't see them as `[Fact, AutoInitShutdown]`.

**Review by BDisp — APPROVED** [review]
Veryyyyy nice work. I love it.
