### PR TITLE
Fixes #3317. v1-Listvew mouse event doesn't cause a SelectedItemChanged event to fire

### LINKED ISSUE #3317: Listvew mouse event doesn't cause a selecteditemchange event to fire
### Discussed in https://github.com/gui-cs/Terminal.Gui/discussions/3316

<div type='discussions-op-text'>

<sup>Originally posted by **dasien** March 13, 2024</sup>
Kind of a beginner here, so this could very likely be something i am doing wrong.  I have a listview on which i am tracking the MouseClick, KeyUp, and SelectedItemChanged events.  When the listview is first loaded, i set the selected item to the first item in the list.  Also, the listview has AllowsMarking and MultiSelect set to true.

The first mouse click in the listview fires the MouseClick event 3 times and it fires the SelectedItemChanged event.  Subsequent mouse clicks still fire the MouseClick event (3 times), but do not fire the SelectedItemChanged event.  Inside the MouseClick, i am checking the listview.SelectedItem, and i do see that number changing from click to click, to the last row on which i clicked, but the SelectedItemChanged event isn't firing.

The issue for me is that i am using that Change event to track the current row in the listview, so that future operations can act on one, or a collection, of items associated with the selected rows.

Similar actions using the keyboard (moving between rows for example) seem to fire both the KeyUp event and SelectedItemChanged events every time.

Is there something i am doing incorrectly or out of order to not get that SelectedItemChanged event to fire?  Alternatively, is there some way to compute the row which was clicked in the listview?  I could then capture the item associated with the row which was clicked and store it in my list of selected items.  Somehow the underlying system knows which row has been clicked, because it is tracking the change to the SelectedItem and marking the correct row with a check mark and highlighting that as the selected row.

Any ideas would be appreciated, and happy to share some code if needed.  It is pretty straightforward for this part, just registering events and putting a breakpoint to check what is firing and when.

Thank you!
</div>

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3317

## Proposed Changes/Todos

- [x] Also fire event if `AllowsMarking` is `true` on click
- [x] Added unit test for proof

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: UnitTests/Views/ListViewTests.cs [hunk 1]
```diff
@@ -545,5 +545,24 @@ tem 2
  tem 3
  tem 4", output);
 		}
+
+		[Fact]
+		public void SelectedItemChanged_Event_Is_Also_Fired_With_AllowsMarking_True_By_Keyboard_Or_Mouse ()
```
Comment (dodexahedron) [inline UnitTests/Views/ListViewTests.cs:550]: Very minor nitpick for consistency with the stack: The dotnet/c# term for events is "raise," not "fire."

**Review by dodexahedron — CHANGES_REQUESTED** [review]
Just one minor nitpick on terminology

**Review by tig — APPROVED** [review]

**Review by tig — APPROVED** [review]
