### PR TITLE
Fixes #3583. `ShadowStyle.Opaque` broke

### LINKED ISSUE #3583: `Button` with `ShadowStyle.Opaque` is broken
Somewhere in the last few PRs (probably the event one), I broke the 3D effect of `Button`::

JMshjZv 1

### PR DESCRIPTION
**Pull request by tig**
## Fixes

- Fixes #3583

## Proposed Changes/Todos

- [x] Fix bug
- [x] Add unit tests

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: UnitTests/View/Adornment/MarginTests.cs [hunk 1]
```diff
@@ -40,4 +40,5 @@ M M
                                             );
         TestHelpers.AssertDriverAttributesAre ("0", null, superView.GetNormalColor ());
     }
+
```
Comment (BDisp) [inline UnitTests/View/Adornment/MarginTests.cs:43]: Nothing relevant has been changed here so it can be undone.

**Review by BDisp — CHANGES_REQUESTED** [review]
LGTM.
