### PR TITLE
Fixes #2571. Wizards background shifts to gray when focusing, looks bad.

### LINKED ISSUE #2571: Wizards background shifts to gray when focusing, looks bad.
**Describe the bug**
Focusing on a wizard window tends to make the background gray which tends to mess up the look.

**To Reproduce**
Open a wizard and click the view. It's most noticeable with textboxes an stuff.

**Expected behavior**
I expected the clicked element, buttons/textboxes/etc,. to change color to show they're focused, instead the whole window went gray.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #2571

## Proposed Changes/Todos

- [x] Allowing containers to use the normal attribute instead of the focused color
- [ ] Adding unit test

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [ ] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

**Comment by BDisp** [comment]
@tig I don't know why this is failing. All the test passed locally.

File: UnitTests/Views/ViewTests.cs [hunk 1]
```diff
@@ -4579,7 +4579,7 @@ public void View_Instance_Use_Attribute_Normal_On_Draw ()
 			TestHelpers.AssertDriverColorsAre (@"
 000000
 011110
-000000", [Colors.TopLevel.Normal, Colors.TopLevel.Focus]);
+000000", new Attribute [] { Colors.TopLevel.Normal, Colors.TopLevel.Focus });
```
Comment (BDisp) [inline UnitTests/Views/ViewTests.cs:4582]: Maybe there is some misconfiguration on the project or on the server. It seems a problem with csharp language version. Change from collection expression to array collection stopped failing.

**Review by tig — APPROVED** [review]

**Review by tig — APPROVED** [review]
