### PR TITLE
Fixes #3966. TextField crashes app when pasting unicode surrogate pair

### LINKED ISSUE #3966: TextField crashes app when pasting unicode surrogate pair
**Describe the bug**
When pasting a 2 char pair e.g. 📄 the TextField crashes with following exception:

```
System.ArgumentOutOfRangeException
Specified argument was out of the range of valid values. (Parameter 'value')
   at System.Text.Rune..ctor(UInt32 value)
   at Terminal.Gui.Key.ToRune(KeyCode key) in D:\Repos\temp\gui.cs\Terminal.Gui\Input\Keyboard\Key.cs:line 349
   at Terminal.Gui.Key.get_AsRune() in D:\Repos\temp\gui.cs\Terminal.Gui\Input\Keyboard\Key.cs:line 156
   at Terminal.Gui.TextField.InsertText(Key a, Boolean usePreTextChangedCursorPos) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TextField.cs:line 1389
   at Terminal.Gui.TextField.InsertText(String toAdd, Boolean useOldCursorPos) in D:\Repos\temp\gui.cs\Terminal.Gui\Views\TextField.cs:line 750
   at Terminal.Gui.ViewsTests.TextFieldTests.TestPasteUnicodeTextField() in D:\Repos\temp\gui.cs\Tests\UnitTests\Views\TextFieldTests.cs:line 1982
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**To Reproduce**

```csharp
    [Fact]
    public void TestPasteUnicodeTextField ()
    {
        var tf = new TextField ();
        //📄
        tf.InsertText ("\ud83d\udcc4");

    }
```

**Expected behavior**
If it is not supported by Terminal.Gui then ignore the paste i.e. paste nothing

### PR DESCRIPTION
**Pull request by BDisp**
## Fixes

- Fixes #3966

## Proposed Changes/Todos

- [x] Add Key(int) constructor
- [x] Add implicit operator Key(int value)
- [x] Allow Key handle non-BMP code points
- [x] Fix TextField non-BMP issues
- [x] Fix TextField PosisionCursor wide chars issue

## Pull Request checklist:

- [x] I've named my PR in the form of "Fixes #issue. Terse description."
- [x] My code follows the [style guidelines of Terminal.Gui](https://github.com/gui-cs/Terminal.Gui/blob/develop/.editorconfig) - if you use Visual Studio, hit `CTRL-K-D` to automatically reformat your files before committing.
- [x] My code follows the [Terminal.Gui library design guidelines](https://github.com/gui-cs/Terminal.Gui/blob/develop/CONTRIBUTING.md)
- [x] I ran `dotnet test` before commit
- [x] I have made corresponding changes to the API documentation (using `///` style comments)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any poor grammar or misspellings
- [x] I conducted basic QA to assure all features are working

### CODE REVIEW

File: Tests/UnitTests/Views/TextFieldTests.cs
Comment (tig) [inline Tests/UnitTests/Views/TextFieldTests.cs:1]: As part of this PR, would you please move any parallelizable unit tests for TextField to the parallelizable unit tests?

**Review by tig — CHANGES_REQUESTED** [review]

File: Tests/UnitTests/Views/TextFieldTests.cs
Comment (BDisp) [reply Tests/UnitTests/Views/TextFieldTests.cs:1]: Sorry I misunderstand. Can you help me to identify how I can check if an unit test can be parallelizable, please? Thanks.

Comment (tig) [reply Tests/UnitTests/Views/TextFieldTests.cs:1]: If it doesn't use AutoInitShutdown, SetupFakeDriver, Application, MouseGrab, or CM it can probably be moved.

Comment (BDisp) [reply Tests/UnitTests/Views/TextFieldTests.cs:1]: Done.

**Review by tig — APPROVED** [review]
LGTM. Ready for merge?

File: Tests/UnitTestsParallelizable/Views/TextFieldTests.cs [hunk 1]
```diff
@@ -0,0 +1,555 @@
...
+    }
+
+    [Fact]
+    public void Space_Does_Not_Raise_Selected ()
+    {
+        TextField tf = new ();
+
+        tf.Selecting += (sender, args) => Assert.Fail ("Selected should not be raied.");
+
+        Application.Top = new ();
```
Comment (tig) [inline Tests/UnitTestsParallelizable/Views/TextFieldTests.cs:52]: Tests that access `Application` cannot be in Parallelizable.

Please refactor this to not use Application.Top. Or, if that's not possible, move it back to `UnitTests`.

In this case, I don't think there's any reason to use `Application`. Just create a superview and call `superView.RaiseNewKeyDownEvent`.

**Review by tig — CHANGES_REQUESTED** [review]
@BDisp, thanks for trying to move these to Parallelizable. However, you need to finish the job by refactoring any tests that use `Application` to not use `Appliacation`. 

If any test in `UnitTests.Parallizable` directly or indirectly sets properties on `Application` it will contaminate other tests and cause seemlingly random test failures.

**Comment by BDisp** [comment]
> LGTM. Ready for merge?

Yes. I think the error in macOS was due to connections problems but I can't rerun the git actions.

image

**Comment by BDisp** [comment]
All checks now passed.

**Review by tig — APPROVED** [review]
